apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp_name_TD
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp_name_TD
  template:
    metadata:
      labels:
        app: myapp_name_TD
    spec:
      containers:
      - name: myapp_name_TD
        image: maciejgum/Image:latest
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: myapp_name_TD-env
          - secretRef:
              name: myapp_name_TD-sec

        resources:
          limits:
            {}

        ports:
        - containerPort: 8080

        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 15

        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 40
          periodSeconds: 15
          
